### ISSUE TITLE
Telegram bridge puppet support

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-dimension#214]
The admin UI for the bridge supports toggling Telegram/Matrix puppetting (independently), but the user UI doesn't expose any puppet options.

The UI principles need to be figured out to accomplish this in a way the user expects, but also to ensure that things like "please enter a chat ID" are replaced with "which chat do you want to bridge? [enter chat ID instead]"

**Comment by ZerataX** [comment]
But I should be able to set these options in the admin api, right?
I can set the provision api fine and bridge/unbridge rooms, but as soon as I try to promote Telegram/Matrix I get:
```python
SequelizeDatabaseError: SQLITE_ERROR: near "WHERE": syntax error
Jun 21 01:13:04 phantom.dmnd.sh nvm_start.sh[24780]:     at Query.formatError (/home/matrix/git/matrix-dimension/node_modules/sequelize/lib/dialects/sqlite/query.js:419:16)
Jun 21 01:13:04 phantom.dmnd.sh nvm_start.sh[24780]:     at Query._handleQueryResponse (/home/matrix/git/matrix-dimension/node_modules/sequelize/lib/dialects/sqlite/query.js:73:18)
Jun 21 01:13:04 phantom.dmnd.sh nvm_start.sh[24780]:     at afterExecute (/home/matrix/git/matrix-dimension/node_modules/sequelize/lib/dialects/sqlite/query.js:247:31)
Jun 21 01:13:04 phantom.dmnd.sh nvm_start.sh[24780]:     at Statement.errBack (/home/matrix/git/matrix-dimension/node_modules/sqlite3/lib/sqlite3.js:16:21)
```

**Comment by turt2live** [comment]
considering it's not fully implemented, no, I wouldn't expect that it works.
