### ISSUE TITLE
Unable to communicate with Dimension due to an unknown error.

### ISSUE THREAD

**Issue by geosphere** [turt2live/matrix-dimension#230]
Hi!
**I'm use matrix-dimension as docker. After first start, all work fine. After restart container I I get an error
`Unable to communicate with Dimension due to an unknown error.`**
Log:
```
Dec-9-2018 06:01:36.910 +00:00 info [index] Dimension is ready!

Dec-9-2018 06:01:54.897 +00:00 info [Webserver] Incoming request: GET /riot?scalar_token=redacted&room_id=!NMMrKPQnDpdewecWzZ%3Amydomain.tld&room_name=testroom&theme=dark

Dec-9-2018 06:02:06.428 +00:00 info [Webserver] Incoming request: GET /api/v1/scalar/account?scalar_token=redacted

Dec-9-2018 06:02:06.434 +00:00 info [MemoryCache] Creating a new cache for namespace: scalar-accounts

Dec-9-2018 06:02:06.474 +00:00 warn [ScalarStore] user @myuser:mydomain.tld is missing a scalar token for upstream 1 (modular)

Dec-9-2018 06:02:06.475 +00:00 error [ScalarService] Invalid token

Error: Invalid token
    at Function.<anonymous> (/home/node/matrix-dimension/build/app/db/ScalarStore.js:48:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/node/matrix-dimension/build/app/db/ScalarStore.js:4:58)
    at <anonymous>

Dec-9-2018 06:02:06.477 +00:00 warn [Webserver] Handling ApiError 401 {"message":"Invalid token","dim_errcode":"D_UNKNOWN"}
```
**Each of the next attempt after container restart - following error:**

```
Dec-9-2018 06:29:28.552 +00:00 warn [Webserver] Handling ApiError 401 {"message":"Invalid token","dim_errcode":"D_UNKNOWN"}

Dec-9-2018 06:29:33.866 +00:00 info [Webserver] Incoming request: OPTIONS /api/v1/scalar/register
Dec-9-2018 06:29:33.869 +00:00 info [Webserver] Incoming request: OPTIONS /api/v1/scalar/register
Dec-9-2018 06:29:33.972 +00:00 info [Webserver] Incoming request: POST /api/v1/scalar/register
Dec-9-2018 06:29:33.976 +00:00 info [MemoryCache] Creating a new cache for namespace: federation

Dec-9-2018 06:29:33.977 +00:00 info [matrix] Using configured federation URL for mydomain.tld

Dec-9-2018 06:29:33.978 +00:00 info [matrix] Doing federated API call: https://mydomain.tld:8448/_matrix/federation/v1/openid/userinfo


Dec-9-2018 06:29:34.063 +00:00 info [Webserver] Incoming request: POST /api/v1/scalar/register
Dec-9-2018 06:29:34.065 +00:00 info [matrix] Doing federated API call: https://mydomain.tld:8448/_matrix/federation/v1/openid/userinfo

Dec-9-2018 06:29:34.186 +00:00 info [ScalarService] Registering @myuser:mydomain.tld for a token at upstream 1 (modular)

Dec-9-2018 06:29:34.190 +00:00 info [ScalarClient] Doing upstream scalar request: https://scalar.vector.im/api/register

Dec-9-2018 06:29:34.205 +00:00 info [ScalarService] Registering @myuser:mydomain.tld for a token at upstream 1 (modular)

Dec-9-2018 06:29:34.206 +00:00 info [ScalarClient] Doing upstream scalar request: https://scalar.vector.im/api/register

Dec-9-2018 06:29:34.875 +00:00 info [Webserver] Incoming request: OPTIONS /api/v1/scalar/register

Dec-9-2018 06:29:34.892 +00:00 info [Webserver] Incoming request: POST /api/v1/scalar/register

Dec-9-2018 06:29:34.894 +00:00 info [matrix] Doing federated API call: https://mydomain.tld:8448/_matrix/federation/v1/openid/userinfo

Dec-9-2018 06:29:34.951 +00:00 info [ScalarService] Registering @myuser:mydomain.tld for a token at upstream 1 (modular)

Dec-9-2018 06:29:34.952 +00:00 info [ScalarClient] Doing upstream scalar request: https://scalar.vector.im/api/register

Dec-9-2018 06:30:04.314 +00:00 error [ScalarClient] Got status code 500 while registering for token

Dec-9-2018 06:30:04.320 +00:00 error [ScalarClient] Got status code 500 while registering for token

ror: Could not get token


    at Request.request [as _callback] (/home/node/matrix-dimension/build/app/scalar/ScalarClient.js:24:28)

    at Request.self.callback (/home/node/matrix-dimension/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/home/node/matrix-dimension/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/home/node/matrix-dimension/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)

ror: Could not get token

    at Request.request [as _callback] (/home/node/matrix-dimension/build/app/scalar/ScalarClient.js:24:28)
    at Request.self.callback (/home/node/matrix-dimension/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/home/node/matrix-dimension/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/home/node/matrix-dimension/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
Dec-9-2018 06:30:05.048 +00:00 error [ScalarClient] Got status code 500 while registering for token
ror: Could not get token
    at Request.request [as _callback] (/home/node/matrix-dimension/build/app/scalar/ScalarClient.js:24:28)
    at Request.self.callback (/home/node/matrix-dimension/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/home/node/matrix-dimension/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/home/node/matrix-dimension/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```
**If I remove dimension.db and recreate container - all work fine until the next restart the container**

**Comment by turt2live** [comment]
It looks like your Dimension is a little older. Does upgrading help solve the problem?

**Comment by smoebody** [comment]
I am getting the same. Using the latest docker-image of `turt2live/matrix-dimension`. After deleting the database and restarting the container everything is working again. maybe the app-version inside the image is too old?

**Comment by turt2live** [comment]
I think this would have been caused by errors upstream, which appear to be resolved now. If it happens again, please open a new issue.
