### ISSUE TITLE
Importing sticker pack from Telegram fails (needs SSLv3 homeserver?)

### ISSUE THREAD

**Issue by shawnanastasio** [turt2live/matrix-dimension#239]
When importing a sticker pack from the admin panel of dimension, the following error messages are encountered:
```
Feb-15-2019 23:15:14.393 -06:00 info [Webserver] Incoming request: POST /api/v1/dimension/admin/stickers/packs/import/telegram?scalar_token=redacted
Feb-15-2019 23:15:14.393 -06:00 info [AdminStickerService] Importing https://t.me/addstickers/TelegramGreatMinds from Telegram for @shawn:matrix.anastas.io
Feb-15-2019 23:15:31.615 -06:00 info [AdminStickerService] Importing sticker from https://api.telegram.org/file/<redacted>/stickers/file_145.webp
object
Feb-15-2019 23:15:32.253 -06:00 info [matrix] Doing client API call: https://matrix.anastas.io/_matrix/media/r0/upload
Feb-15-2019 23:15:32.259 -06:00 error [matrix] Error calling /_matrix/media/r0/upload
Feb-15-2019 23:15:32.259 -06:00 error [matrix] write EPROTO 140521624443776:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:802:

Error: write EPROTO 140521624443776:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:802:

    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
Feb-15-2019 23:15:32.259 -06:00 error [AdminStickerService] write EPROTO 140521624443776:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:802:

Error: write EPROTO 140521624443776:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:802:

    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
Feb-15-2019 23:15:32.280 -06:00 warn [Webserver] Handling ApiError 500 {"message":"Error importing stickers","dim_errcode":"D_UNKNOWN"}
```

It appears that it's attempting to upload the stickers to my homeserver over SSLv3 which I have explicitly disabled in my nginx configuration.

**Comment by Natureshadow** [comment]
I already get this issue when starting dimension forthe first time. It might not be SSLv3, but also TLSv1.x with some unsupported algorithm (like an unsupported ECDSA curve).

For my homeserver using a Let's Encrypt ECDSA certificate, I get this error whe nstarting dimension, both from self-compiled git version and in Docker.
