### ISSUE TITLE
Docker image database unable open and attempt to write a readonly database

### ISSUE THREAD

**Issue by longfan3** [turt2live/matrix-dimension#265]
when i start dimension with turt2live/matrix-dimension:latest,i got this error message：

    { SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file
        at Database.connections.(anonymous function).lib.Database.err (/home/node/matrix-dimension/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:66:63)
      name: 'SequelizeConnectionError',
      parent: { Error: SQLITE_CANTOPEN: unable to open database file errno: 14, code: 'SQLITE_CANTOPEN' },
      original: { Error: SQLITE_CANTOPEN: unable to open database file errno: 14, code: 'SQLITE_CANTOPEN' } }

then i create file in dimension/store/dimension.db, i got this error message:

    { SequelizeDatabaseError: SQLITE_READONLY: attempt to write a readonly database
        at Query.formatError (/home/node/matrix-dimension/node_modules/sequelize/lib/dialects/sqlite/query.js:423:16)
        at Statement.afterExecute (/home/node/matrix-dimension/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
        at Statement.replacement (/home/node/matrix-dimension/node_modules/sqlite3/lib/trace.js:19:31)
        at Statement.replacement (/home/node/matrix-dimension/node_modules/sqlite3/lib/trace.js:19:31)
      name: 'SequelizeDatabaseError',
      parent:
      { Error: SQLITE_READONLY: attempt to write a readonly database
        errno: 8,
        code: 'SQLITE_READONLY',
        sql: 'CREATE TABLE IF NOT EXISTS `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY);' },
      original:
      { Error: SQLITE_READONLY: attempt to write a readonly database
        errno: 8,
        code: 'SQLITE_READONLY',
        sql: 'CREATE TABLE IF NOT EXISTS `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY);' },
      sql: 'CREATE TABLE IF NOT EXISTS `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY);' }

is there some permission error in the Dockerfile?

**Comment by turt2live** [comment]
This looks like the volume wasn't created with the right permissions, so it can't write to the folder in the first place. I think you're ultimately being hit with #224 which might fix the issue.

**Comment by longfan3** [comment]
it's works, thanks!
