### ISSUE TITLE
no widgets available

### ISSUE THREAD

**Issue by vmario89** [turt2live/matrix-dimension#269]
Hi,
i checked out the current master branch but when starting dimension i cannot see any widgets anymore:

![grafik](https://user-images.githubusercontent.com/5631071/55551317-cf29e780-56da-11e9-8149-149222fb5e3d.png)

i dont see any serious errors in the log :(

**Comment by turt2live** [comment]
There should be errors in either the Dimension log or browser javascript console which highlight the problem.

**Comment by vmario89** [comment]
Hey,
javascript did not return something. But i had a second look into dimension.log and grepped out the following error statements after restarting:

```
Apr-9-2019 00:56:29.416 +02:00 error [BridgeStore] Failed to load configuration for bridge: Telegram Bridge
Apr-9-2019 00:56:29.417 +02:00 error [BridgeStore] No bridges or too many bridges found
Error: No bridges or too many bridges found
    at TelegramBridge.<anonymous> (/opt/matrix-dimension/build/app/bridges/TelegramBridge.js:22:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/matrix-dimension/build/app/bridges/TelegramBridge.js:4:58)
Apr-9-2019 00:56:29.424 +02:00 error [BridgeStore] Failed to load configuration for bridge: Webhook Bridge
Apr-9-2019 00:56:29.425 +02:00 error [BridgeStore] No bridges or too many bridges found
Error: No bridges or too many bridges found
    at WebhooksBridge.<anonymous> (/opt/matrix-dimension/build/app/bridges/WebhooksBridge.js:22:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/matrix-dimension/build/app/bridges/WebhooksBridge.js:4:58)
Apr-9-2019 00:56:29.701 +02:00 error [GitterBridge] Got status code 404 when calling https://scalar.vector.im/api/bridges/gitter/_matrix/provision/getlink
Apr-9-2019 00:56:29.702 +02:00 error [GitterBridge] {"message":"Bridge returned HTTP 404 Not Found: Link not found"}
Apr-9-2019 00:56:29.823 +02:00 info [SlackBridge] Doing upstream Slack Bridge request: https://scalar.vector.im/api/bridges/slack/_matrix/provision/getlink
Apr-9-2019 00:56:29.916 +02:00 error [SlackBridge] Got status code 404 when calling https://scalar.vector.im/api/bridges/slack/_matrix/provision/getlink
Apr-9-2019 00:56:29.917 +02:00 error [SlackBridge] {"message":"Bridge returned HTTP 404 Not Found: Link not found"}
Error: No bridges or too many bridges found
    at TelegramBridge.<anonymous> (/opt/matrix-dimension/build/app/bridges/TelegramBridge.js:22:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/matrix-dimension/build/app/bridges/TelegramBridge.js:4:58)
Apr-9-2019 00:57:00.380 +02:00 error [AdminAppserviceService] Appservice not found
Error: Appservice not found
    at Function.<anonymous> (/opt/matrix-dimension/build/app/db/AppserviceStore.js:90:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/matrix-dimension/build/app/db/AppserviceStore.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Apr-9-2019 00:57:03.573 +02:00 error [AdminAppserviceService] Appservice not found
Error: Appservice not found
    at Function.<anonymous> (/opt/matrix-dimension/build/app/db/AppserviceStore.js:90:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/matrix-dimension/build/app/db/AppserviceStore.js:4:58)
Apr-9-2019 00:57:05.829 +02:00 error [AdminAppserviceService] Appservice not found
Error: Appservice not found
    at Function.<anonymous> (/opt/matrix-dimension/build/app/db/AppserviceStore.js:90:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/matrix-dimension/build/app/db/AppserviceStore.js:4:58)
```

im not sure about the error "Appservice not found". production.yaml contains correct information about tokens and it is registered in homeserver.yaml in synapse. Maybe some compilation problem?

regards, Mario

**Comment by turt2live** [comment]
hmm, if this is a fairly fresh install you could try shutting down Dimension then deleting its database (after making a backup), then starting it again. If that's not an option, please restart Dimension, open the admin panel, and send me the full log from Dimension.

**Comment by vmario89** [comment]
Hi,
i dont know why, but now it works again with the widgets. i did not change anything :-D
