### ISSUE TITLE
Problems with goneb rss and travisci bots

### ISSUE THREAD

**Issue by targodan** [turt2live/matrix-dimension#275]
# Problem

I can't add RSS or TravisCi bots anymore, see screenshot:

![Capture](https://user-images.githubusercontent.com/6468902/56144541-d9819680-5fa2-11e9-83b5-56c05ab9f8da.PNG)

However the Giphy and Wikipedia bots still work, i.e. I can add them, remove them and use them after they have been added.

The admin panel claims the appservice config seems to work though.

![Capture](https://user-images.githubusercontent.com/6468902/56144797-50b72a80-5fa3-11e9-9b79-665de2cfe6ae.PNG)

# Setup

Got synapse, goneb and dimension running in their respective docker containers connected via an overlay network.

Yes, HS, dimension and goneb are all selfhosted.

Dimension image has been created 16 hours ago as of writing this.

# Logs

I found this in the dimension logs:

```
Apr-15-2019 14:27:26.368 +00:00 info [Webserver] Incoming request: GET /api/v1/scalar/account?v=1.1&scalar_token=redacted
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/node/matrix-dimension/node_modules/send/index.js:390:13)
    at SendStream.send (/home/node/matrix-dimension/node_modules/send/index.js:618:10)
    at onstat (/home/node/matrix-dimension/node_modules/send/index.js:730:10)
    at FSReqWrap.oncomplete (fs.js:171:5)
Apr-15-2019 14:27:26.392 +00:00 info [Webserver] Incoming request: GET /api/v1/dimension/admin/check?scalar_token=redacted
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/node/matrix-dimension/node_modules/send/index.js:390:13)
    at SendStream.send (/home/node/matrix-dimension/node_modules/send/index.js:618:10)
    at onstat (/home/node/matrix-dimension/node_modules/send/index.js:730:10)
    at FSReqWrap.oncomplete (fs.js:171:5)
Apr-15-2019 14:27:26.401 +00:00 info [Webserver] Incoming request: GET /api/v1/dimension/stickers/packs?scalar_token=redacted
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/node/matrix-dimension/node_modules/send/index.js:390:13)
    at SendStream.send (/home/node/matrix-dimension/node_modules/send/index.js:618:10)
    at onstat (/home/node/matrix-dimension/node_modules/send/index.js:730:10)
    at FSReqWrap.oncomplete (fs.js:171:5)
Apr-15-2019 14:27:26.411 +00:00 info [Webserver] Incoming request: GET /api/v1/dimension/integrations/room/!JwvgwMjYDAWteyumBv:targodan.de?scalar_token=redacted
Apr-15-2019 14:27:26.526 +00:00 info [BridgeStore] Checking bridge configuration: IRC Bridge
Apr-15-2019 14:27:26.543 +00:00 error [BridgeStore] Failed to load configuration for bridge: IRC Bridge
Apr-15-2019 14:27:26.543 +00:00 error [BridgeStore] Cannot read property 'scalarToken' of null
TypeError: Cannot read property 'scalarToken' of null
    at IrcBridge.<anonymous> (/home/node/matrix-dimension/build/app/bridges/IrcBridge.js:268:40)
    at Generator.next (<anonymous>)
    at fulfilled (/home/node/matrix-dimension/build/app/bridges/IrcBridge.js:4:58)
    at <anonymous>
Apr-15-2019 14:27:26.545 +00:00 info [BridgeStore] Checking bridge configuration: Telegram Bridge
Apr-15-2019 14:27:26.554 +00:00 info [BridgeStore] Checking bridge configuration: Webhook Bridge
Apr-15-2019 14:27:26.560 +00:00 info [BridgeStore] Checking bridge configuration: Gitter Bridge
Apr-15-2019 14:27:26.566 +00:00 info [BridgeStore] Checking bridge configuration: Slack Bridge
[object Object]
Apr-15-2019 14:27:31.149 +00:00 info [Webserver] Incoming request: GET /api/v1/dimension/admin/version?scalar_token=redacted
Apr-15-2019 14:27:31.151 +00:00 info [Webserver] Incoming request: GET /api/v1/dimension/admin/config?scalar_token=redacted
Apr-15-2019 14:27:31.152 +00:00 info [matrix] Doing client API call: http://synapse:8008/_matrix/client/r0/account/whoami
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/node/matrix-dimension/node_modules/send/index.js:390:13)
    at SendStream.send (/home/node/matrix-dimension/node_modules/send/index.js:618:10)
    at onstat (/home/node/matrix-dimension/node_modules/send/index.js:730:10)
    at FSReqWrap.oncomplete (fs.js:171:5)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/node/matrix-dimension/node_modules/send/index.js:390:13)
    at SendStream.send (/home/node/matrix-dimension/node_modules/send/index.js:618:10)
    at onstat (/home/node/matrix-dimension/node_modules/send/index.js:730:10)
    at FSReqWrap.oncomplete (fs.js:171:5)
Apr-15-2019 14:27:32.841 +00:00 info [Webserver] Incoming request: GET /api/v1/dimension/admin/upstreams/all?scalar_token=redacted
Apr-15-2019 14:27:32.843 +00:00 info [Webserver] Incoming request: GET /api/v1/dimension/admin/appservices/all?scalar_token=redacted
Apr-15-2019 14:27:32.844 +00:00 info [Webserver] Incoming request: GET /api/v1/dimension/admin/neb/all?scalar_token=redacted
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/node/matrix-dimension/node_modules/send/index.js:390:13)
    at SendStream.send (/home/node/matrix-dimension/node_modules/send/index.js:618:10)
    at onstat (/home/node/matrix-dimension/node_modules/send/index.js:730:10)
    at FSReqWrap.oncomplete (fs.js:171:5)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/node/matrix-dimension/node_modules/send/index.js:390:13)
    at SendStream.send (/home/node/matrix-dimension/node_modules/send/index.js:618:10)
    at onstat (/home/node/matrix-dimension/node_modules/send/index.js:730:10)
    at FSReqWrap.oncomplete (fs.js:171:5)
Apr-15-2019 14:27:32.854 +00:00 error [AdminAppserviceService] Appservice not found
Error: Appservice not found
    at Function.<anonymous> (/home/node/matrix-dimension/build/app/db/AppserviceStore.js:90:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/node/matrix-dimension/build/app/db/AppserviceStore.js:4:58)
    at <anonymous>
```

**Comment by targodan** [comment]
Not sure if this is relevant or not. I may have kicked a goneb bot from a room at some point instead of removing it via the integrations page.

**Comment by turt2live** [comment]
Fixed by https://github.com/turt2live/matrix-dimension/commit/be66dd04f977ec13dc4dd41a9914a7f7fa821647

**Comment by targodan** [comment]
I can confirm, the problem is solved! 👍 
Thank you.
