### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by airblag** [turt2live/matrix-dimension#281]
I found the same errors in the issues #275 and #240 but I cannot say exactly where it comes from in my installation (updated to commit be66dd04f977ec13dc4dd41a9914a7f7fa821647).

Every time I switch room in riot, the following error comes 3 times

```Mai 03 12:53:02 mort npm[23994]: Error: Can't set headers after they are sent.
Mai 03 12:53:02 mort npm[23994]:     at SendStream.headersAlreadySent (/home/dimension/matrix-dimension/node_modules/send/index.js:390:13)
Mai 03 12:53:02 mort npm[23994]:     at SendStream.send (/home/dimension/matrix-dimension/node_modules/send/index.js:618:10)
Mai 03 12:53:02 mort npm[23994]:     at onstat (/home/dimension/matrix-dimension/node_modules/send/index.js:730:10)
Mai 03 12:53:02 mort npm[23994]:     at FSReqWrap.oncomplete (fs.js:154:5)
```

Some times it appears only once.

I didn't found any problem related to this error on the user side.

Dimension is running behind nginx.

Is it a bug or did I miss something ?

**Comment by turt2live** [comment]
The error is normally harmless - are you seeing any other side effects?

**Comment by airblag** [comment]
no, i don't see anything not working because of that, but it's filling my log files :)

**Comment by yingziwu** [comment]
> The error is normally harmless - are you seeing any other side effects?

I found this error will cause that transmission is closed early.

## Environment

```
debian version: 10.7
nodejs version: v12.20.1
npm version: 6.14.10
```

## Reproduction process

Run the following command on the same machine of dimension:

```
watch -d "curl -v --connect-to ::192.168.100.1:8184  "http://dimension.bgme.bid/api/v1/dimension/stickers/packs?scalar_token=[token]" 1>/dev/null "
```
You will get the following results:

normal:
```
curl -v --connect-to ::192.168.100.1:8184  http://dimension.bgme.bid/api/v1/dimension/stickers/packs?scalar_token=IiZBW4DZQZ287Vr9sBnDvq7vd 1>/...  git: Mon Jan 25 10:58:57 2021

* Expire in 0 ms for 6 (transfer 0x5568e0ba9f90)
* Connecting to hostname: 192.168.100.1
* Connecting to port: 8184
*   Trying 192.168.100.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x5568e0ba9f90)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 192.168.100.1 (192.168.100.1) port 8184 (#0)
> GET /api/v1/dimension/stickers/packs?scalar_token=IiZBW4DZQZ287Vr9sBnDvq7vd HTTP/1.1
> Host: dimension.bgme.bid
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
< Content-Type: application/json; charset=utf-8
< Content-Length: 169598
< ETag: W/"2967e-l3+xBmGWM4sf7W+6cdgvCMWXWtc"
< Date: Mon, 25 Jan 2021 10:58:57 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
{ [44689 bytes data]
*100  165k  100  165k    0     0  4732k      0 --:--:-- --:--:-- --:--:-- 4732k
* Connection #0 to host 192.168.100.1 left intact
```

error:
```
curl -v --connect-to ::192.168.100.1:8184  http://dimension.bgme.bid/api/v1/dimension/stickers/packs?scalar_token=IiZBW4DZQZ287Vr9sBnDvq7vd 1>/...  git: Mon Jan 25 10:58:09 2021

* Expire in 0 ms for 6 (transfer 0x564d649e7f90)
* Connecting to hostname: 192.168.100.1
* Connecting to port: 8184
*   Trying 192.168.100.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x564d649e7f90)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 192.168.100.1 (192.168.100.1) port 8184 (#0)
> GET /api/v1/dimension/stickers/packs?scalar_token=IiZBW4DZQZ287Vr9sBnDvq7vd HTTP/1.1
> Host: dimension.bgme.bid
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
< Content-Type: application/json; charset=utf-8
< Content-Length: 169598
< ETag: W/"2967e-l3+xBmGWM4sf7W+6cdgvCMWXWtc"
< Date: Mon, 25 Jan 2021 10:58:10 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
{ [44689 bytes data]
* transfer closed with 57325 bytes remaining to read
* 66  165k   66  109k    0     0  4568k      0 --:--:-- --:--:-- --:--:-- 4568k
* Closing connection 0
curl: (18) transfer closed with 57325 bytes remaining to read
```

**Comment by yingziwu** [comment]
Really weird.
Change the `ExecStart` of `matrix-dimension.service` from `/usr/bin/npm run start:app` to `/usr/bin/npm run start:app`, although there is still `Error: Can't set headers after they are sent.` in the log, But curl no longer appears: `curl: (18) transfer closed with xxxxx bytes remaining to read.`

**Comment by yingziwu** [comment]
/etc/systemd/system/matrix-dimension.service

Before:
```
[Unit]
Description=Integrations server for Matrix.org
After=network.target

[Service]
ExecStart=/usr/bin/npm run start:app
WorkingDirectory=/opt/matrix-dimension
Environment=NODE_ENV=production

# Restart timing
Restart=always
RestartSec=60

# Output to syslog
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=matrix-dimension

# User & group to run service as
User=matrix-dimension
Group=matrix-dimension

[Install]
WantedBy=default.target
```

After:
```
[Unit]
Description=Integrations server for Matrix.org
After=network.target

[Service]
ExecStart=/usr/bin/npm run start:app
WorkingDirectory=/opt/matrix-dimension
Environment=NODE_ENV=production

# Restart timing
Restart=always
RestartSec=60

# Output to syslog
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=matrix-dimension

# User & group to run service as
User=matrix-dimension
Group=matrix-dimension

[Install]
WantedBy=default.target
````

**Comment by rakshazi** [comment]
Hello, tried to work with Dimension on element android and got error "User does not have permissions", but i use admin user and i can do that on element web.

The error in log:
```
Feb 14 15:52:36 matrix matrix-dimension[26675]: Error: Can't set headers after they are sent.
Feb 14 15:52:36 matrix matrix-dimension[26675]:     at SendStream.headersAlreadySent (/home/node/matrix-dimension/node_modules/send/index.js:390:13)
Feb 14 15:52:36 matrix matrix-dimension[26675]:     at SendStream.send (/home/node/matrix-dimension/node_modules/send/index.js:617:10)
Feb 14 15:52:36 matrix matrix-dimension[26675]:     at onstat (/home/node/matrix-dimension/node_modules/send/index.js:729:10)
Feb 14 15:52:36 matrix matrix-dimension[26675]:     at FSReqCallback.oncomplete (fs.js:167:5)
```

**Comment by IF-Adin** [comment]
I have the same problem. Stickers do not work for me at all. They all return a 502.

**Comment by IF-Adin** [comment]
Jun 12 18:48:21 matrix-dimension[20622]: Error: Can't set headers after they are sent.
Jun 12 18:48:21 matrix-dimension[20622]:     at SendStream.headersAlreadySent (/home/node/matrix-dimension/node_modules/send/index.js:390:13)
Jun 12 18:48:21 matrix-dimension[20622]:     at SendStream.send (/home/node/matrix-dimension/node_modules/send/index.js:617:10)
Jun 12 18:48:21 matrix-dimension[20622]:     at onstat (/home/node/matrix-dimension/node_modules/send/index.js:729:10)

This completely block the displaying of all stickers. Federation is set up correctly and the federation tester as well as the extension tester work fine.

**Comment by pratikbalar** [comment]
+1

**Comment by gaelgatelement** [comment]
Same error after setting a k8s probe on the dimension pod : 

```
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/dimension/health/heartbeat
              port: 8184
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/dimension/health/heartbeat
              port: 8184
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 3
```

```
Tue, 22 Mar 2022 18:29:02 GMT [INFO] [DimensionHealthService] Heartbeat called
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/node/matrix-dimension/node_modules/send/index.js:390:13)
    at SendStream.send (/home/node/matrix-dimension/node_modules/send/index.js:617:10)
    at onstat (/home/node/matrix-dimension/node_modules/send/index.js:729:10)
    at FSReqCallback.oncomplete (fs.js:193:5)

```
