### ISSUE TITLE
Problems in npm run build

### ISSUE THREAD

**Issue by rioloo** [turt2live/matrix-dimension#355]
# git show
commit 9e2393cecac3aabdc3d6d7236a4c139d6fe9ff6d (HEAD -> master, origin/master, origin/HEAD)
Merge: 3e8ad80 c232264
Author: Travis Ralston <travpc@gmail.com>
Date:   Thu Apr 30 10:25:04 2020 -0600

    Merge pull request #346 from turt2live/dependabot/npm_and_yarn/jquery-3.5.0
    
    Bump jquery from 3.4.1 to 3.5.0

# npm --version
6.14.4
# node --version
v10.21.0

# npm run build

> matrix-dimension@1.0.0 build /usr/local/matrix/matrix-dimension
> npm run-script build:web && npm run-script build:app

> matrix-dimension@1.0.0 build:web /usr/local/matrix/matrix-dimension
> rimraf build/web && webpack --mode production --progress --profile --bail

Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
    at validate (/usr/local/matrix/matrix-dimension/node_modules/copy-webpack-plugin/node_modules/schema-utils/dist/validate.js:96:11)
    at new CopyPlugin (/usr/local/matrix/matrix-dimension/node_modules/copy-webpack-plugin/dist/index.js:24:30)
    at module.exports (/usr/local/matrix/matrix-dimension/webpack.config.js:127:9)
    at handleFunction (/usr/local/matrix/matrix-dimension/node_modules/webpack-cli/bin/utils/prepareOptions.js:21:13)
    at prepareOptions (/usr/local/matrix/matrix-dimension/node_modules/webpack-cli/bin/utils/prepareOptions.js:9:5)
    at requireConfig (/usr/local/matrix/matrix-dimension/node_modules/webpack-cli/bin/utils/convert-argv.js:119:14)
    at /usr/local/matrix/matrix-dimension/node_modules/webpack-cli/bin/utils/convert-argv.js:125:17
    at Array.forEach (<anonymous>)
    at module.exports (/usr/local/matrix/matrix-dimension/node_modules/webpack-cli/bin/utils/convert-argv.js:123:15)
    at yargs.parse (/usr/local/matrix/matrix-dimension/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/usr/local/matrix/matrix-dimension/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /usr/local/matrix/matrix-dimension/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/usr/local/matrix/matrix-dimension/node_modules/webpack-cli/bin/cli.js:365:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/matrix/matrix-dimension/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! matrix-dimension@1.0.0 build:web: `rimraf build/web && webpack --mode production --progress --profile --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the matrix-dimension@1.0.0 build:web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-18T13_44_23_116Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! matrix-dimension@1.0.0 build: `npm run-script build:web && npm run-script build:app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the matrix-dimension@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-18T13_44_23_130Z-debug.log

**Comment by BrotherIAmPinnedHere** [comment]
I've got the same issue with NPM 7.20.5 and node 12.18.4.


Invalid options object. Copy Plugin has been initialized using an options object                                    that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, filter?, tran                                   sformAll?, toType?, force?, priority?, info?, transform?, transformPath?, noErro                                   rOnMissing? }, ...] (should not have fewer than 1 item)
ValidationError: Invalid options object. Copy Plugin has been initialized using                                    an options object that does not match the API schema.
    at validate (/root/matrix-dimension/node_modules/copy-webpack-plugin/node_mo                                   dules/schema-utils/dist/validate.js:105:11)
    at new CopyPlugin (/root/matrix-dimension/node_modules/copy-webpack-plugin/d                                   ist/index.js:38:31)
    at module.exports (/root/matrix-dimension/webpack.config.js:127:9)
    at handleFunction (/root/matrix-dimension/node_modules/webpack-cli/bin/utils                                   /prepareOptions.js:21:13)
    at prepareOptions (/root/matrix-dimension/node_modules/webpack-cli/bin/utils                                   /prepareOptions.js:9:5)
    at requireConfig (/root/matrix-dimension/node_modules/webpack-cli/bin/utils/                                   convert-argv.js:119:14)
    at /root/matrix-dimension/node_modules/webpack-cli/bin/utils/convert-argv.js                                   :125:17
    at Array.forEach (<anonymous>)
    at module.exports (/root/matrix-dimension/node_modules/webpack-cli/bin/utils                                   /convert-argv.js:123:15)
    at /root/matrix-dimension/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/root/matrix-dimension/node_modules/webpack-cli/node_module                                   s/yargs/yargs.js:567:18)
    at /root/matrix-dimension/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/root/matrix-dimension/node_modules/webpack-cli/bin/c                                   li.js:365:3)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at runCli (/root/matrix-dimension/node_modules/webpack/bin/webpack.js:69:2)
    at Object.<anonymous> (/root/matrix-dimension/node_modules/webpack/bin/webpa                                   ck.js:162:2)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js                                   :71:12)
    at internal/main/run_main_module.js:17:47
