### ISSUE TITLE
go-neb RSS integration broken

### ISSUE THREAD

**Issue by bmanturner** [turt2live/matrix-dimension#408]
## To Reproduce

Step by step instructions to reproduce the behavior:

1. Install dimension
2. Install go-neb with RSS support
3. Point dimension at go-neb
4. Register dimension appservice for go-neb
5. Click 'test' and receive successful message
6. Activate RSS bot
7. Open Integrations manager
8. Observe RSS Bot says it is "offline or unavailable"

## Expected behavior

I expect the RSS Bot to work

## Describe the bug

The RSS Bot does not work

## Details

Deployed via `matrix-docker-ansible-deploy` to Ubuntu 20.04

**Comment by bmanturner** [comment]
This error occurs when attempting to create the RSS user for the first time

```

Apr 01 21:30:37 matrix matrix-dimension[231286]: Apr-1-2021 21:30:37.706 +00:00 info [AppserviceStore] Registering to own @_botler_rss_notifications_=40beeman=3afoglet.io:foglet.io in appservice dimension-ITJnsk6bCBmZN3XMwExI2GugN
Apr 01 21:30:37 matrix matrix-dimension[231286]: Apr-1-2021 21:30:37.707 +00:00 info [matrix] Doing client API call: http://matrix-nginx-proxy:12080/_matrix/client/r0/register
Apr 01 21:30:37 matrix matrix-dimension[231286]: Apr-1-2021 21:30:37.776 +00:00 info [AppserviceStore] Successfully registered @_botler_rss_notifications_=40beeman=3afoglet.io:foglet.io
Apr 01 21:30:37 matrix matrix-dimension[231286]: Apr-1-2021 21:30:37.787 +00:00 verbose [DimensionStore [SQL]] Executing (default): INSERT INTO "dimension_appservice_users" ("id","accessToken","appserviceId") VALUES ($1,$2,$3) RETURNING *;
Apr 01 21:30:37 matrix matrix-dimension[231286]: Apr-1-2021 21:30:37.796 +00:00 error [NebStore] value too long for type character varying(255)
Apr 01 21:30:37 matrix matrix-dimension[231286]: SequelizeDatabaseError: value too long for type character varying(255)
Apr 01 21:30:37 matrix matrix-dimension[231286]:     at Query.formatError (/home/node/matrix-dimension/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
Apr 01 21:30:37 matrix matrix-dimension[231286]:     at /home/node/matrix-dimension/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
Apr 01 21:30:37 matrix matrix-dimension[231286]:     at tryCatcher (/home/node/matrix-dimension/node_modules/bluebird/js/release/util.js:16:23)
Apr 01 21:30:37 matrix matrix-dimension[231286]:     at Promise._settlePromiseFromHandler (/home/node/matrix-dimension/node_modules/bluebird/js/release/promise.js:517:31)
Apr 01 21:30:37 matrix matrix-dimension[231286]:     at Promise._settlePromise (/home/node/matrix-dimension/node_modules/bluebird/js/release/promise.js:574:18)
Apr 01 21:30:37 matrix matrix-dimension[231286]:     at Promise._settlePromise0 (/home/node/matrix-dimension/node_modules/bluebird/js/release/promise.js:619:10)
Apr 01 21:30:37 matrix matrix-dimension[231286]:     at Promise._settlePromises (/home/node/matrix-dimension/node_modules/bluebird/js/release/promise.js:695:18)
Apr 01 21:30:37 matrix matrix-dimension[231286]:     at _drainQueueStep (/home/node/matrix-dimension/node_modules/bluebird/js/release/async.js:138:12)
Apr 01 21:30:37 matrix matrix-dimension[231286]:     at _drainQueue (/home/node/matrix-dimension/node_modules/bluebird/js/release/async.js:131:9)
Apr 01 21:30:37 matrix matrix-dimension[231286]:     at Async._drainQueues (/home/node/matrix-dimension/node_modules/bluebird/js/release/async.js:147:5)
Apr 01 21:30:37 matrix matrix-dimension[231286]:     at Immediate.Async.drainQueues [as _onImmediate] (/home/node/matrix-dimension/node_modules/bluebird/js/release/async.js:17:14)
Apr 01 21:30:37 matrix matrix-dimension[231286]:     at processImmediate (internal/timers.js:456:21)
```
